baseurl = "/"
languageCode = "en-us"
title = "Flavius Alecu"
theme = "PaperMod"
googleAnalytics = ""
paginate = 10
sectionPagesMenu = "main"

disableKinds = ["RSS"]

[params.profileMode]
  enabled = true
  title = " "

[[params.socialIcons]]
  name = "LinkedIn"
  url = "https://linkedin.com/in/alecu"

[[menu.main]]
	name = "Work"
	weight = 2
	identifier = "work"
	url = "/work"
